### ISSUE TITLE
Issues with “Why not just use git?”

### ISSUE THREAD

**Issue by wking** [maxogden/dat#121] opened 2014-06-02 22:30 UTC
[In the what-is-dat docs][1] you list some reasons to not use Git:
> * Large numbers of commits add significant overhead. A repository with millions of commits might take minutes or hours to complete a git status check.

I expect `git status` times to scale with working directory size, not number of commits.  I don't have benchmarks to back this up though.

> * To quote Linus Torvalds, "Git fundamentally never really looks at less than the whole repo", e.g. if you have a repository of a million documents you can't simply clone and track a subset.

You can if you use submodules.  Although that's still publisher-driven subsetting, and not consumer-driven subsetting.

> * git stores the full history of a repository. What if you only want to store the latest version of each row in a database and not a copy of every version? This needs to be optional (for disk space reasons).

You can if you use shallow clones.

I agree that a data-centered version control system can probably make optimizations that aren't available to the source-code-focused Git.  However, I'd like to see *that* discussed (e.g. why are dat commits lighter weight?  Or does dat not have commits at all?) instead of attributing dubious technical limitations to Git.  Of course, maybe you're claims are valid, in which case, they might just need a bit more supporting material to convince folks like me ;).

[1]: https://github.com/maxogden/dat/blob/master/docs/what-is-dat.md#why-not-just-use-git

**Comment by paulharris** [comment] 2015-06-18 02:43
daff + git can diff and merge CSV files.

I think this thread has valid questions, because I am deciding between git and dat for storing and merging some data.

**Comment by karissa** [comment] 2015-06-19 00:19
Git has some fundamental problems with the way it works under the hood. From the whitepaper:


"Git was designed to track changes to relatively small text files, so many datasets, especially those that change often, are cumbersome to use with Git. Two years ago, Facebook created a test Git repository to explore its limits, and found that at 1.3 million files with 15 GB of data, Git takes upwards of 40 minutes to respond to a simple command [7]. To fix this performance problem with Git, there is an extension called the 'Git Large File Storage (LFS)' released in 2015 [8], and Git-Annex [9], written in Haskell. We believe these extensions are not designed well for data science use cases, which often require support for features like real-time data feeds, partial replication or parallel downloading."

https://github.com/maxogden/dat/blob/master/docs/whitepaper.md

**Comment by paulharris** [comment] 2015-06-19 03:04
This is how I'm reading it,

So, for dat's case,
dat solves the problem with two approaches:

1) import into a table format and then ability to download changes.  Which
is basically database + replication.  But that requires the data to be in a
tabular format that is importable, AND assumes the format can be diff'd
during import and detect minimal changes automatically.

2) the read/write system just keeps versions of the files.   Just treated
as binary opaque blobs?  or  with block level dedup?   Which hopefully
works when 1 character is added to the start of the file (ie dedup can
handle blocks becoming unaligned, ie like rsync's rolling checksums).  Or
custom differs/mergers?   Otherwise .dat folder gets very large with time?

So, for # 1, a dataset is like a MariaDB database table with a push and
pull interface (or in MongoDB terms, _changes replication stream).  And,
can do some query and filters, like OPeNDAP.org.

For # 2, seems like a file store with historic snapshots for versioning.
No diffing, merging, etc.   ie for "attachments" that are replaced
wholesale.

And # 1 is where all the streaming diffing merging happens.

The whitepaper seems to focus on # 1 entirely.

Did I read it correctly?
cheers,
Paul

**Comment by thadguidry** [comment] 2015-06-19 03:34
I would simply evoke the idea of ...

 dat comes with a server and set of client technologies that provides a
Distributed Data Store (storage)

 (It is unlike Git, Bittorrent, HDFS, etc. which provide Distributed File
Storage, Distributed File Systems, or Source/Version Control Systems)

dat lets you store and distribute versions of your data, while also
allowing exploration, sharing, and updating of your data.


Why complicate the core philosophy with dissimilar backend goals that might
be provided by various plugins ?  Just stick to explaining the core dat
philosophy and your golden.


Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by joehand** [comment] 2016-06-17 18:37
This issue was moved to datproject/discussions#44

**Closed by joehand** 2016-06-17 18:37 UTC
Labels: discussion
