### ISSUE TITLE
Data not downloading in "client" connection

### ISSUE THREAD

**Issue by cfobel** [maxogden/dat#465] opened 2016-03-15 14:47 UTC
Hello,

I am running `dat` version 9.8.2, as reported by `dat -v`, which I installed by cloning the `dat` GitHub repository and running `npm link` with revision 0ea2dce7136740b33b5229b3fc8599f1746f2802.

I have tried running a very simple configuration, but am having trouble getting data to download using the `dat dat://<hash>` command.

## Console 1 ##

 1. Create a directory named `source` containing a single empty file named `hello-world.txt`.
 2. From within `source`, run `dat link`.
 3. Copy `dat://<hash>` URI.

## Console 2 ##

 1. Create `target` directory.
 2. Change into `target` directory.
 3. Run `dat dat://<hash>` with hash copied from **Console 1**.

## Expected behvaiour ##

New `source` directory created in `target`, containing file named `hello-world.txt`.

## Observed behaviour ##
 
 - Consoles indicate connection through an increase in the number of connected sources.
 - Nothing created in `target` directory.

Here is a screencast showing the issue:

![dat-issue](https://cloud.githubusercontent.com/assets/823355/13781562/35e614f4-ea9a-11e5-862f-819a3f27ec52.gif)

**Comment by waldoj** [comment] 2016-03-15 15:20
A+ BUG REPORT WOULD READ AGAIN.

**Comment by joehand** [comment] 2016-03-15 16:22
@cfobel this may have to do with the entire folder and file being 0 bytes. This was a bug that was recently fixed in [hyperdrive](https://github.com/mafintosh/hyperdrive/) (a dat dependency). 

There are two things you can do that will help figure out the cause of the bug:

1. We need to make sure the hyperdrive module is up to date (4.0.0 is the latest). The straightforward way to do this is delete and reinstall your `node_modules` inside your dat cloned repository.  Once this is done, try linking/downloading your folder again.
2. If 1. doesn't work, try doing it with non-empty folder/files. This will help to figure out if its a 0 bytes bug or something else (windows, perhaps). 

Dat is connecting and transferring metadata (since we can see how much should be transferred). But then something is going wrong...

**Comment by karissa** [comment] 2016-03-17 19:55
@cfobel I am having trouble reproducing this with the latest versions of the dependencies. Could you let us know if updating the dependencies (described by @joehand) helped?

It is clearly possible this is a windows bug, so your feedback will be useful!

**Comment by cfobel** [comment] 2016-03-18 13:19
Thanks @joehand and @karissa .  I have been swamped at work the last few days, but plan to test out your suggestions this afternoon (EDT).

On a side note, I am an experienced developer, but have not had a chance to use `node`.  Is there any easy way to dump out the versions of packages that are being used?  For now, I've been manually checking package versions by looking at the `package.json` file in the corresponding directory in `node_modules`.  However, it's a bit tedious and I'm hoping that there is a much simpler way to do this (i.e., something similar to `pip freeze` or `pip list`).  I did see [this][1], where they mention `npm shinkwrap`.  Any suggestions?

I manually checked the version of `hyperdrive` installed in `dat/node_modules` by looking in the `hyperdrive/package.json` and it was 4.0.0.  However, I noticed that the latest version of `hyperdrive` that I cloned from GitHub was 4.1.0.  Perhaps this version will help...

I'll keep you posted :)


[1]: http://stackoverflow.com/questions/17576243/pip-freeze-for-node-and-npm

**Comment by joehand** [comment] 2016-03-18 15:56
@cfobel, yep! `npm list` will do almost the same as `pip list` (except it shows the whole tree). `npm list --depth=0` will show immediate dependencies, a bit easier to read if you are looking just for hyperdrive.

The 0 byte bug was fixed on hyperdrive before 4.0.0, so it may be another windows bug you are running into.

**Comment by joehand** [comment] 2016-06-17 18:49
We've changed a lot since the 9.8 version. Please reopen if you experience issues with the new version. Thanks!

**Closed by joehand** 2016-06-17 18:49 UTC
Labels: ready
